[theme]
primaryColor = "#2E7D32"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
maxUploadSize = 10
enableCORS = true
port = 8501

[browser]
gatherUsageStats = false
